version: "3.9"

services:
  fast-backend:
    build: .
    container_name: fast-backend
    hostname: fastpractice
    volumes:
      - ./app/:/app
    ports:
      - 8000:8000
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env
    command: ["uvicorn","main:app","--host","0.0.0.0","--port","8000","--reload"]
  database:
    image: postgres:latest
    container_name: database
    hostname: postgresdb
    user: postgres
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: tabaresbryan39@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  postgres-volume:
  pgadmin-data: